curl -O https://cs.stanford.edu/~karpathy/convnetjs/demo/mnist/mnist_batch_1.png
curl -O https://cs.stanford.edu/~karpathy/convnetjs/demo/mnist/mnist_batch_2.png
curl -O https://cs.stanford.edu/~karpathy/convnetjs/demo/mnist/mnist_batch_3.png
curl -O https://cs.stanford.edu/~karpathy/convnetjs/demo/mnist/mnist_batch_4.png
curl -O https://cs.stanford.edu/~karpathy/convnetjs/demo/mnist/mnist_batch_5.png
curl -O https://cs.stanford.edu/~karpathy/convnetjs/demo/mnist/mnist_batch_6.png
curl -O https://cs.stanford.edu/~karpathy/convnetjs/demo/mnist/mnist_batch_7.png
curl -O https://cs.stanford.edu/~karpathy/convnetjs/demo/mnist/mnist_batch_8.png
curl -O https://cs.stanford.edu/~karpathy/convnetjs/demo/mnist/mnist_batch_9.png
curl -O https://cs.stanford.edu/~karpathy/convnetjs/demo/mnist/mnist_batch_10.png
curl -O https://cs.stanford.edu/~karpathy/convnetjs/demo/mnist/mnist_batch_11.png
curl -O https://cs.stanford.edu/~karpathy/convnetjs/demo/mnist/mnist_batch_12.png
curl -O https://cs.stanford.edu/~karpathy/convnetjs/demo/mnist/mnist_batch_13.png
curl -O https://cs.stanford.edu/~karpathy/convnetjs/demo/mnist/mnist_batch_14.png
curl -O https://cs.stanford.edu/~karpathy/convnetjs/demo/mnist/mnist_batch_15.png
curl -O https://cs.stanford.edu/~karpathy/convnetjs/demo/mnist/mnist_batch_16.png
curl -O https://cs.stanford.edu/~karpathy/convnetjs/demo/mnist/mnist_batch_17.png
curl -O https://cs.stanford.edu/~karpathy/convnetjs/demo/mnist/mnist_batch_18.png
curl -O https://cs.stanford.edu/~karpathy/convnetjs/demo/mnist/mnist_batch_19.png
curl -O https://cs.stanford.edu/~karpathy/convnetjs/demo/mnist/mnist_batch_20.png